### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by jeffgdotorg** [Baspla/netbox_reservations#1]
Hi there, product manager for NetBox Labs here. I would love to list this plugin in our public [plugins catalog](https://netboxlabs.com/netbox-plugins/), but we do require that listed plugins have a top-level LICENSE file.

An update to work with NetBox 4.0 would be nice too, but the license is the thing actually blocking my ability to add it to the registry since that column is not nullable.

**Comment by Baspla** [comment]
Hi, thanks for including my project. 👍
I added a [MIT License](https://github.com/Baspla/netbox_reservations/blob/main/LICENSE) to the root folder.
I'll try to get around to testing it with 4.0 when i find the time for it.
